
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Nojonghyun  ## put your name
title: 'GENERATIVE AI DEVELOPER'  ## your title
location: YONGIN, KOREA


## Social Profiles




# Update all the sections by editing the files inside _includes folder.
